image: docker:19.03.1

services:
  - docker:19.03.1-dind

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"


stages:
  - build
  - test
  - push
  - deploy

# see how to login at https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#using-the-gitlab-container-registry
before_script:
  - docker login -u $DOCKERHUB_LOGIN -p $DOCKERHUB_TOKEN

build-image:
  stage: build
  tags: 
    - dind
  script:
    - docker build . --tag $DOCKERHUB_LOGIN/$IMAGE_NAME

push-image:
  stage: push
  tags:
    - dind
  script:
    - docker push $DOCKERHUB_LOGIN/$IMAGE_NAME

